# Generated by Django 4.1.4 on 2022-12-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='not available', max_length=50),
        ),
    ]
